/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilankantin;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.Frame;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.lang.Math;
/**
 *
 * @author riald
 */
public class DaftarPesananKantin extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form DaftarPesananTenant
     */
    public DaftarPesananKantin() {
        initComponents();
        setupPesananTable();
        setupAksiTombol();
        autoResizeColumns();
    }
    private void setupAksiTombol() {
        jButton1.addActionListener(e -> jButton1ActionPerformed(e)); 
        jButton2.addActionListener(e -> jButton2ActionPerformed(e));
    }
    public void autoResizeColumns() {
        if (jTable1 == null || jTable1.getRowCount() == 0) return;
        
        TableColumnModel columnModel = jTable1.getColumnModel();
        
        for (int column = 0; column < jTable1.getColumnCount(); column++) {
            int width = 50;
            
            TableCellRenderer headerRenderer = jTable1.getTableHeader().getDefaultRenderer();
            Component headerComp = headerRenderer.getTableCellRendererComponent(
                    jTable1, columnModel.getColumn(column).getHeaderValue(), false, false, 0, 0);
            width = Math.max(width, headerComp.getPreferredSize().width);
            
            for (int row = 0; row < jTable1.getRowCount(); row++) {
                TableCellRenderer renderer = jTable1.getCellRenderer(row, column);
                Component comp = jTable1.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + jTable1.getIntercellSpacing().width, width); 
            }
            columnModel.getColumn(column).setPreferredWidth(width + 10);
        }
    }
    
    private void setupPesananTable() {
        String[] columnNames = {"ID", "NAMA PENGGUNA", "WAKTU ORDER", "NAMA PESANAN", "HARGA SATUAN", "JUMLAH", "TOTAL", "STATUS"}; 
        tableModel = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(tableModel);
        loadPesananData();
        setupAksiTombol();
        
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        TableColumnModel columnModel = jTable1.getColumnModel();
        
        for (int column = 0; column < jTable1.getColumnCount(); column++) {
            int width = 50;
            
            TableCellRenderer headerRenderer = jTable1.getTableHeader().getDefaultRenderer();
            Component headerComp = headerRenderer.getTableCellRendererComponent(jTable1, columnModel.getColumn(column).getHeaderValue(), false, false, 0, 0);
            width = Math.max(width, headerComp.getPreferredSize().width);
            
            for (int row = 0; row < jTable1.getRowCount(); row++) {
                TableCellRenderer renderer = jTable1.getCellRenderer(row, column);
                Component comp = jTable1.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + jTable1.getIntercellSpacing().width, width);
            }
            columnModel.getColumn(column).setPreferredWidth(width + 10);
        }
        setupAksiTombol();
    }
    
    public void loadPesananData() {
        tableModel.setRowCount(0);
        Object[][] data = {
            {101, "Aryo ", "2025-12-01 10:30", "Ayam Geprek", 20000, 2, 40000, "Baru"},
            {101, "Aryo ", "2025-12-01 10:30", "Es Teh Manis", 5000, 1, 5000, "Baru"},
            {102, "Diana ", "2025-12-01 10:45", "Nasi Goreng", 18000, 1, 18000, "Baru"},
            {103, "Rialdi ", "2025-11-30 15:00", "Jus Alpukat", 15000, 1, 15000, "Diproses"}
        };
        for (Object[] row : data) {
            tableModel.addRow(row);
        }
        setupAksiTombol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("DAFTAR PESANAN MASUK");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAMA PENGGUNA", "WAKTU OREDER", "HARGA SATUAN", "JUMLAH", "TOTAL", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Proses Pesanan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Siap Diambil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih pesanan yang akan diproses.", 
                                          "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String currentStatus = tableModel.getValueAt(selectedRow, 7).toString();

        if (!currentStatus.equals("Baru")) {
            JOptionPane.showMessageDialog(this, "Pesanan sudah diproses atau selesai.", 
                                          "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        tableModel.setValueAt("Diproses", selectedRow, 7);
        JOptionPane.showMessageDialog(this, "Pesanan dipindahkan ke status 'Diproses'.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih pesanan yang sudah selesai.", 
                                          "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String currentStatus = tableModel.getValueAt(selectedRow, 7).toString();

        // Validasi: Pesanan harus Diproses terlebih dahulu
        if (currentStatus.equals("Baru")) {
            JOptionPane.showMessageDialog(this, "Pesanan harus diproses terlebih dahulu.", 
                                          "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        tableModel.setValueAt("Siap Diambil", selectedRow, 7);
        JOptionPane.showMessageDialog(this, "Status pesanan diubah menjadi 'Siap Diambil'.");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
