/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilankantin;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author riald
 */
public class EditProfilKantin extends javax.swing.JDialog {
    private java.awt.Frame parentFrame;
    private JTextField namaField, noHpField, namaKantinField;
    private JButton simpanBtn, batalBtn;

    /**
     * Creates new form EditProfilTenant
     */
    public EditProfilKantin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parentFrame = parent;
        initComponents();
        setTitle("Edit Profil Kantin");
        mapComponents(); 
        
        this.setSize(350, 300); // <-- Atur ukuran yang cukup untuk form
        this.revalidate();
        this.repaint();
        
        setLocationRelativeTo(parent);
        loadDataProfil();
        setupAksiTombol();
    }
    private void mapComponents() {
        this.namaField = jTextField1;
        this.noHpField = jTextField2;
        this.namaKantinField = jTextField3;

        this.simpanBtn = jButton1;
        this.batalBtn = jButton2;
    }
    private void loadDataProfil() {
        namaField.setText("      ");
        noHpField.setText("      ");
        namaKantinField.setText("      ");
    }
    private void setupAksiTombol() {
        simpanBtn.addActionListener(e -> simpanBtnActionPerformed(e));
        batalBtn.addActionListener(e -> batalBtnActionPerformed(e));
    }
    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String namaBaru = namaField.getText();
        String noHpBaru = noHpField.getText();
        
        if (!noHpBaru.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Nomor HP harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Data profil berhasil diperbarui!");
        this.dispose();
    }
    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("EDIT PROFIL KANTIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 20, -1, -1));

        jLabel2.setText("Nama Tenant:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 62, -1, -1));

        jLabel3.setText("No. Telepon:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 102, -1, -1));

        jLabel4.setText("Nama Kantin:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 142, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 59, -1, -1));

        jTextField2.setText("jTextField1");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 99, -1, -1));

        jTextField3.setText("jTextField1");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 139, -1, -1));

        jButton1.setText("SIMPAN");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 179, -1, -1));

        jButton2.setText("BATAL");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 179, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
