/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilankantin;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.Frame;
/**
 *
 * @author riald
 */
public class ManajemenMenu extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    /**
     * Creates new form ManajemenMenu
     */
    public ManajemenMenu() {
        initComponents();
        setupMenuTable();
    }
    
    private void setupMenuTable() {
        String[] columnNames = {"ID", "NAMA MENU", "STOK", "HARGA"};
        tableModel = new DefaultTableModel(columnNames, 0);
        
        jTable1.setModel(tableModel); 
        loadMenuData();
        setupAksiTombol();
    }
    
    public void loadMenuData() {
        tableModel.setRowCount(0);
        
        Object[][] data = {
            {1, "Ayam Geprek Pedas", 15, 20000}, 
            {2, "Nasi Goreng Spesial", 25, 18000}, 
            {3, "Es Teh Manis", 50, 5000}       
        };
        for (Object[] row : data) {
            tableModel.addRow(row);
        }
    }
    
    private void setupAksiTombol() {
        jButton1.addActionListener(e -> jButton1ActionPerformed(e));
        jButton2.addActionListener(e -> jButton2ActionPerformed(e));
        jButton3.addActionListener(e -> jButton3ActionPerformed(e));
    }
    private void addItemToMenuTable(String nama, String harga, String stok) {
        int newId = tableModel.getRowCount() + 1;
        try {
            int hargaInt = Integer.parseInt(harga);
            int stokInt = Integer.parseInt(stok);
            tableModel.addRow(new Object[]{newId, nama, stokInt, hargaInt});
            
            JOptionPane.showMessageDialog(this, "Menu " + nama + " berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka!", "Error Input", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("MANAJEMEN MENU KANTIN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAMA MENU", "HARGA", "STOK"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Tambah Menu");

        jButton2.setText("Edit Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        
        JTextField namaField = new JTextField(20);
        JTextField hargaField = new JTextField(20);
        JTextField stokField = new JTextField(20);
        
        JPanel inputForm = new JPanel(new GridLayout(4, 2, 5, 5));
        inputForm.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        inputForm.add(new JLabel("Nama Menu:"));
        inputForm.add(namaField);
        inputForm.add(new JLabel("Harga (Rp):"));
        inputForm.add(hargaField);
        inputForm.add(new JLabel("Stok:"));
        inputForm.add(stokField);
        inputForm.add(new JLabel("")); // Spacer

        JButton simpanButton = new JButton("Simpan");
        JButton batalButton = new JButton("Batal");
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttonPanel.add(simpanButton);
        buttonPanel.add(batalButton);
        
        JDialog tambahDialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this),"Tambah Item Menu",true);
        
        tambahDialog.getContentPane().setLayout(new BorderLayout());
        tambahDialog.getContentPane().add(inputForm, BorderLayout.CENTER);
        tambahDialog.getContentPane().add(buttonPanel, BorderLayout.SOUTH);
    
        tambahDialog.pack();
        tambahDialog.setLocationRelativeTo(this);
        
        simpanButton.addActionListener(e -> {
            String nama = namaField.getText();
            String harga = hargaField.getText();
            String stok = stokField.getText();
            
            if (nama.trim().isEmpty() || harga.trim().isEmpty() || stok.trim().isEmpty()) {
                JOptionPane.showMessageDialog(tambahDialog, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            addItemToMenuTable(nama, harga, stok);
            tambahDialog.dispose();
        });
        
        batalButton.addActionListener(e -> {
            tambahDialog.dispose();
        });
        
        tambahDialog.setVisible(true);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih menu yang ingin diedit terlebih dahulu.","Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String namaLama = tableModel.getValueAt(selectedRow, 1).toString();
        String stokLama = tableModel.getValueAt(selectedRow, 2).toString();
        String hargaLama = tableModel.getValueAt(selectedRow, 3).toString();
        
        JTextField namaField = new JTextField(namaLama);
        JTextField stokField = new JTextField(stokLama);
        JTextField hargaField = new JTextField(hargaLama);
        
        JButton simpanButton = new JButton("Simpan");
        JButton batalButton = new JButton("Batal");
        JPanel inputForm = new JPanel(new GridLayout(4, 2, 5, 5));
        inputForm.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttonPanel.add(simpanButton);
        buttonPanel.add(batalButton);
        
        inputForm.add(new JLabel("Nama Menu:"));
        inputForm.add(namaField);
        inputForm.add(new JLabel("Stok:"));
        inputForm.add(stokField);
        inputForm.add(new JLabel("Harga:"));
        inputForm.add(hargaField);
        
        JDialog editDialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this),"Edit Item Menu: " + namaLama,true);
        
        editDialog.getContentPane().setLayout(new BorderLayout());
        editDialog.getContentPane().add(inputForm, BorderLayout.CENTER);
        editDialog.getContentPane().add(buttonPanel, BorderLayout.SOUTH);

        editDialog.pack();
        editDialog.setLocationRelativeTo(this);
        
        simpanButton.addActionListener(e -> {
            try {
                String namaBaru = namaField.getText();
                int stokBaru = Integer.parseInt(stokField.getText());
                int hargaBaru = Integer.parseInt(hargaField.getText());

                // Perbarui data LANGSUNG di model tabel (Kolom: 1=Nama, 2=Stok, 3=Harga)
                tableModel.setValueAt(namaBaru, selectedRow, 1);
                tableModel.setValueAt(stokBaru, selectedRow, 2);
                tableModel.setValueAt(hargaBaru, selectedRow, 3);

                editDialog.dispose();
                JOptionPane.showMessageDialog(this, "Menu " + namaBaru + " berhasil diperbarui.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(editDialog, "Harga dan Stok harus berupa angka!", "Error Input", JOptionPane.ERROR_MESSAGE);
            }
        });
        batalButton.addActionListener(e -> {
            editDialog.dispose();
        });
        editDialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih menu yang ingin dihapus terlebih dahulu.", 
                                      "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        String namaMenu = tableModel.getValueAt(selectedRow, 1).toString();
        
        int confirm = JOptionPane.showConfirmDialog(this,"Anda yakin ingin menghapus menu " + namaMenu + "?","Konfirmasi Hapus",JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            tableModel.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Menu " + namaMenu + " berhasil dihapus.","Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
