/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilanuser;

/**
 *
 * @author aryop
 */
import sistemkantinonline.tampilanuser.HomeUser;
import sistemkantinonline.tampilanuser.PesananPanel;
import sistemkantinonline.tampilanuser.ItemKeranjang;
import sistemkantinonline.tampilanuser.DataPesanan;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import sistemkantinonline.BuatNomorPesanan;
import javax.swing.JOptionPane;

public class Checkout extends javax.swing.JPanel {

    // default metode = Tunai
    private String metodeDipilih = "Tunai";

    public Checkout() {
        initComponents();
        isiTabel();
        aturStyleTable();
    }

    private void isiTabel() {
        var model = (javax.swing.table.DefaultTableModel) overviewTabel.getModel();
        model.setRowCount(0);

        for (ItemKeranjang i : Cart.getItems()) {
            model.addRow(new Object[]{
                i.getNama(),
                i.getHarga(),
                i.getJumlah(),
                i.getTotal()
            });
        }
    }


    private int hitungTotal() {
        int t = 0;
        for (ItemKeranjang i : Cart.getItems()) {
            t += i.getTotal();
        }
        return t;
    }

    private void aturStyleTable() {
        // FONT HEADER
        JTableHeader header = overviewTabel.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 16));

        // FONT ISI TABEL
        overviewTabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        overviewTabel.setRowHeight(28);

        // CENTER ISI TABEL (semua kolom)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < overviewTabel.getColumnCount(); i++) {
            overviewTabel.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        metodeButtonGroup = new javax.swing.ButtonGroup();
        alamatPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overviewTabel = new javax.swing.JTable();
        batalBtn = new javax.swing.JButton();
        pesanBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tunaiBtn = new javax.swing.JButton();
        transferBtn = new javax.swing.JButton();
        qrisBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        alamatPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Alamat Pengantaran");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jl.Bangau Sakti");

        javax.swing.GroupLayout alamatPanelLayout = new javax.swing.GroupLayout(alamatPanel);
        alamatPanel.setLayout(alamatPanelLayout);
        alamatPanelLayout.setHorizontalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(723, Short.MAX_VALUE))
        );
        alamatPanelLayout.setVerticalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12))
        );

        overviewTabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        overviewTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(overviewTabel);

        batalBtn.setBackground(new java.awt.Color(51, 153, 255));
        batalBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        batalBtn.setForeground(new java.awt.Color(255, 255, 255));
        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        pesanBtn.setBackground(new java.awt.Color(51, 153, 255));
        pesanBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pesanBtn.setForeground(new java.awt.Color(255, 255, 255));
        pesanBtn.setText("Pesan");
        pesanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Metode Pembayaran");

        tunaiBtn.setBackground(new java.awt.Color(51, 153, 255));
        tunaiBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tunaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        tunaiBtn.setText("Tunai");
        metodeButtonGroup.add(tunaiBtn);
        tunaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiBtnActionPerformed(evt);
            }
        });

        transferBtn.setBackground(new java.awt.Color(51, 153, 255));
        transferBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        transferBtn.setForeground(new java.awt.Color(255, 255, 255));
        transferBtn.setText(" Transfer Bank");
        metodeButtonGroup.add(transferBtn);
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        qrisBtn.setBackground(new java.awt.Color(51, 153, 255));
        qrisBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qrisBtn.setForeground(new java.awt.Color(255, 255, 255));
        qrisBtn.setText("Qris");
        metodeButtonGroup.add(qrisBtn);
        qrisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrisBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Detail Pesanan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("> Checkout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alamatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tunaiBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transferBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qrisBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(batalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pesanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(alamatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tunaiBtn)
                    .addComponent(transferBtn)
                    .addComponent(qrisBtn)
                    .addComponent(pesanBtn)
                    .addComponent(batalBtn))
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalBtnActionPerformed

    private void pesanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanBtnActionPerformed

        if (Cart.getItems().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang kosong!");
            return;
        }

        int no = BuatNomorPesanan.next();
        String alamat = jLabel2.getText();
        String metode = metodeDipilih;

        List<PesananItem> listItem = new ArrayList<>();
        for (ItemKeranjang i : Cart.getItems()) {
            listItem.add(i.toPesananItem());
        }

        int total = hitungTotal();

        Pesanan p = new Pesanan(no, alamat, metode, total, listItem);
        DataPesanan.tambahPesanan(p);

        Cart.kosongkan();

        var parent = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent instanceof HomeUser home) {
            home.changeMainPanel(new PesananPanel()); // pakai panel final
        }
    
    }//GEN-LAST:event_pesanBtnActionPerformed

    private void tunaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiBtnActionPerformed
        metodeDipilih = "Tunai";        // TODO add your handling code here:
    }//GEN-LAST:event_tunaiBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        metodeDipilih = "Transfer Bank";        // TODO add your handling code here:
    }//GEN-LAST:event_transferBtnActionPerformed

    private void qrisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrisBtnActionPerformed
        metodeDipilih = "Qris";        // TODO add your handling code here:
    }//GEN-LAST:event_qrisBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alamatPanel;
    private javax.swing.JButton batalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup metodeButtonGroup;
    private javax.swing.JTable overviewTabel;
    private javax.swing.JButton pesanBtn;
    private javax.swing.JButton qrisBtn;
    private javax.swing.JButton transferBtn;
    private javax.swing.JButton tunaiBtn;
    // End of variables declaration//GEN-END:variables
}
