/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilanuser;

import sistemkantinonline.Menu;

/**
 *
 * @author aryop
 */
public class DaftarMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form DaftarMenuPanel1
     */
    public DaftarMenuPanel() {
        initComponents();
        isiMenuDummy();
    }

    public void isiMenuDummy() {
        contentPanel.removeAll();

        contentPanel.add(new MenuCardPanel("Ayam Geprek", 20000, "ayam-geprek.jpg"));
        contentPanel.add(new MenuCardPanel("Nasi Goreng", 15000, "ayam-geprek.jpeg"));
        contentPanel.add(new MenuCardPanel("Mie Goreng", 14000, "ayam-geprek.jpeg"));
        contentPanel.add(new MenuCardPanel("Mie Goreng", 14000, "ayam-geprek.jpeg"));
        contentPanel.add(new MenuCardPanel("Mie Goreng", 14000, "ayam-geprek.jpeg"));
        contentPanel.add(new MenuCardPanel("Mie Goreng", 14000, "ayam-geprek.jpeg"));
        contentPanel.add(new MenuCardPanel("Mie Goreng", 14000, "ayam-geprek.jpeg"));
        contentPanel.add(new MenuCardPanel("Mie Goreng", 14000, "ayam-geprek.jpeg"));

        contentPanel.revalidate();
        contentPanel.repaint();
    }

    public void tambahMenuCard(String nama, int harga, String pathGambar) {
        MenuCardPanel card = new MenuCardPanel(nama, harga, pathGambar);
        contentPanel.add(card);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    public void setMenuList(java.util.List<Menu> menus) {
        contentPanel.removeAll();

        for (Menu m : menus) {
            MenuCardPanel card = new MenuCardPanel(
                    m.getNama(),
                    m.getHarga(), 
                    m.getPathGambar()
            );
            contentPanel.add(card);
        }

        contentPanel.revalidate();
        contentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contentPanel.setLayout(new java.awt.GridLayout(0, 4, 16, 16));
        jScrollPane1.setViewportView(contentPanel);

        searchTextField.setText("Cari menu");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addGap(16, 16, 16))
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
