package sistemkantinonline.tampilanuser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author aryo
 */
import sistemkantinonline.tampilanuser.ItemKeranjang;

public class DetailMenuDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailMenuDialog.class.getName());

    /**
     * Creates new form detailMenu
     */
    public DetailMenuDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setData(String nama, int harga) {
        
        namaDetailLabel.setText(nama);
        String hargaMakanan = String.valueOf(harga);
        hargaDetailLabel.setText("Rp " + hargaMakanan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masukKeranjangBtn = new javax.swing.JButton();
        namaDetailLabel = new javax.swing.JLabel();
        deskripsiLabel = new javax.swing.JLabel();
        beliBtn = new javax.swing.JButton();
        hargaDetailLabel = new javax.swing.JLabel();
        fotoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Menu");
        setBackground(new java.awt.Color(255, 255, 255));

        masukKeranjangBtn.setBackground(new java.awt.Color(255, 255, 255));
        masukKeranjangBtn.setForeground(new java.awt.Color(0, 0, 0));
        masukKeranjangBtn.setText("Masuk Keranjang");
        masukKeranjangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukKeranjangBtnActionPerformed(evt);
            }
        });

        namaDetailLabel.setFont(new java.awt.Font("Fira Sans", 0, 22)); // NOI18N
        namaDetailLabel.setText("Ayam Geprek");

        deskripsiLabel.setText("deskripsi makanan.....");

        beliBtn.setBackground(new java.awt.Color(51, 153, 255));
        beliBtn.setForeground(new java.awt.Color(255, 255, 255));
        beliBtn.setText("Beli");
        beliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBtnActionPerformed(evt);
            }
        });

        hargaDetailLabel.setFont(new java.awt.Font("Fira Sans", 0, 20)); // NOI18N
        hargaDetailLabel.setText("sample 1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaDetailLabel)
                            .addComponent(deskripsiLabel)
                            .addComponent(hargaDetailLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(masukKeranjangBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(beliBtn)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaDetailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deskripsiLabel)
                        .addGap(63, 63, 63)
                        .addComponent(hargaDetailLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beliBtn)
                            .addComponent(masukKeranjangBtn))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBtnActionPerformed

// 1. Ambil nama & harga dari label
    String nama = namaDetailLabel.getText();

        // hargaDetailLabel: contoh "Rp 10.000"
        String hargaText = hargaDetailLabel.getText()
                .replace("Rp", "")
                .replace(".", "")
                .trim();
        int harga = Integer.parseInt(hargaText);

        // 2. Tambahkan ke Cart, default jumlah = 1
        Cart.tambahItem(new ItemKeranjang(nama, harga, 1));

        // 3. Cari parent window (HomeUser)
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);

        // 4. Tutup dialog dulu
        this.dispose();

        // 5. Kalau parent-nya HomeUser, ganti main panel ke Checkout
        if (parent instanceof HomeUser) {
            HomeUser home = (HomeUser) parent;
            home.changeMainPanel(new Checkout());
        }
    }//GEN-LAST:event_beliBtnActionPerformed

    private void masukKeranjangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukKeranjangBtnActionPerformed
        String nama = namaDetailLabel.getText();
        String hargaText = hargaDetailLabel.getText()
                .replace("Rp", "")
                .replace(".", "")
                .trim();
        int harga = Integer.parseInt(hargaText);

        Cart.tambahItem(new ItemKeranjang(nama, harga, 1));

        // opsional: cuma tutup detail
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_masukKeranjangBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DetailMenuDialog dialog = new DetailMenuDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliBtn;
    private javax.swing.JLabel deskripsiLabel;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JLabel hargaDetailLabel;
    private javax.swing.JButton masukKeranjangBtn;
    private javax.swing.JLabel namaDetailLabel;
    // End of variables declaration//GEN-END:variables
}
