/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilanuser;

/**
 *
 * @author aryop
 */
public class MenuCardPanel extends javax.swing.JPanel {

    private String namaMenu;
    private double hargaMenu;

    /**
     * Creates new form MenuCardPanel
     */
    public MenuCardPanel(String nama, double harga) {
        initComponents();
        setData(nama, harga);
    }

    public MenuCardPanel(String nama, double harga, String pathGambar) {
        initComponents();
        setData(nama, harga, pathGambar);
    }

    public void setData(String nama, double harga) {
        this.namaMenu = nama;
        this.hargaMenu = harga;

        namaLabel.setText(nama);
        hargaLabel.setText("Rp " + harga);
    }

    public void setData(String nama, double harga, String pathGambar) {
        this.namaMenu = nama;
        this.hargaMenu = harga;
        namaLabel.setText(nama);
        hargaLabel.setText("Rp " + formatHarga(harga));

        if (pathGambar != null && !pathGambar.isEmpty()) {
            java.net.URL imgUrl = getClass().getResource("/images/" + pathGambar);

            if (imgUrl != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                java.awt.Image img = icon.getImage().getScaledInstance(
                        280, 200, java.awt.Image.SCALE_SMOOTH
                );
                fotoLabel.setIcon(new javax.swing.ImageIcon(img));
            } else {
                System.err.println("Gambar tidak ditemukan: " + pathGambar);
            }
        }
    }

    private String formatHarga(double harga) {
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        nf.setGroupingUsed(true);
        return nf.format(harga);
    }

    private void tampilkanDetail() {
        // cari window induk (HomeUser / frame lain)
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);

        // pastikan parent-nya Frame
        java.awt.Frame frameParent = null;
        if (parentWindow instanceof java.awt.Frame) {
            frameParent = (java.awt.Frame) parentWindow;
        }

        // bikin dialog detail
        DetailMenuDialog dialog = new DetailMenuDialog(frameParent, true);

        // DetailMenuDialog.setData saat ini pakai int,
        // jadi kalau hargaMenu double tinggal cast atau round:
        int hargaInt = (int) Math.round(hargaMenu);

        dialog.setData(namaMenu, hargaInt);
        dialog.setLocationRelativeTo(parentWindow);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fotoLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        fotoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayam-geprek.jpeg"))); // NOI18N
        fotoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLabel.setText("Nama menu");

        hargaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hargaLabel.setText("Harga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(namaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(hargaLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(fotoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaLabel)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tampilkanDetail();// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JLabel namaLabel;
    // End of variables declaration//GEN-END:variables
}
