/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilanuser;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.BoxLayout;
import javax.swing.Box;
import java.awt.Color;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.BorderLayout;


/**
 *
 * @author aryo
 */
public class PesananPanel extends javax.swing.JPanel {

    private JPanel listPanel;

    /**
     * Creates new form pesananPanel
     */
    public PesananPanel() {
        initComponents();
        initCustom();
        loadData();
    }

    private void initCustom() {
        listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        scrollPane.setViewportView(listPanel);
    }

    private void loadData() {
        listPanel.removeAll();

        for (Pesanan p : DataPesanan.getRiwayat()) {

            PesananCardPanel card = new PesananCardPanel();
            card.setData(
                    p.getNoPesanan(),
                    p.getAlamat(),
                    p.getMetode(),
                    p.getItems(),
                    p.getTotal()
            );

            JPanel wrapper = new JPanel(new BorderLayout());
            wrapper.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20));
            wrapper.add(card, BorderLayout.CENTER);

            listPanel.add(card);
            listPanel.add(Box.createVerticalStrut(15));
        }

        listPanel.revalidate();
        listPanel.repaint();
    }
//
//    // tambah 1 pesanan (1 card) ke dalam panel
//    public void tambahPesanan(int noPesanan, String alamat, String metodePembayaran, List<PesananItem> items, int total) {
//        PesananCardPanel card = new PesananCardPanel();
//        card.setData(noPesanan, alamat, metodePembayaran, items, total);
//
//        listPanel.add(card);
//        listPanel.add(Box.createVerticalStrut(15)); // jarak antar card
//
//        listPanel.revalidate();
//        listPanel.repaint();
//    }
//
//    public void resetPesanan() {
//        listPanel.removeAll();
//        listPanel.revalidate();
//        listPanel.repaint();
//    }
//
//    // inisialisasi panel penampung card pesanan
//    private void initCustomComponents() {
//        listPanel = new JPanel();
//        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
//        listPanel.setBackground(Color.WHITE);
//
//        // pasang listPanel ke scrollPane yang sudah ada di form
//        scrollPane.setViewportView(listPanel);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
