/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemkantinonline.tampilanuser;

import sistemkantinonline.dataakun.AkunUser;
import sistemkantinonline.dataakun.SessionUser;

/**
 *
 * @author aryop
 */
public class ProfilPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfilPanel
     */
    public ProfilPanel() {
        initComponents();
        isiDataProfilDariSession();
    }

    public void refreshData() {
        AkunUser akun = SessionUser.getCurrentUser();
        namaLabel.setText(akun.getNama());
        noHpLabel.setText(akun.getNoHp());
        fakultasLabel.setText(akun.getFakultas());
        jurusanLabel.setText(akun.getJurusan());
        prodiLabel.setText(akun.getProdi());
        alamatDefaultLabel.setText(akun.getAlamatDefault());
    }

    private void isiDataProfilDariSession() {
        AkunUser akun = SessionUser.getCurrentUser();

        if (akun == null) {
            // belum login / dipanggil tanpa session
            return;
        }

        namaLabel.setText(akun.getNama());
        noHpLabel.setText(akun.getNoHp());
        kategoriLabel.setText(akun.getKategori());
        fakultasLabel.setText(akun.getFakultas());
        jurusanLabel.setText(akun.getJurusan());
        prodiLabel.setText(akun.getProdi());
        alamatDefaultLabel.setText(akun.getAlamatDefault());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ppLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        noHpLabel = new javax.swing.JLabel();
        fakultas = new javax.swing.JLabel();
        jurusan = new javax.swing.JLabel();
        prodi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kategoriLabel = new javax.swing.JLabel();
        fakultasLabel = new javax.swing.JLabel();
        jurusanLabel = new javax.swing.JLabel();
        prodiLabel = new javax.swing.JLabel();
        alamatDefaultLabel = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 235, 235));
        setPreferredSize(new java.awt.Dimension(942, 600));

        profilLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        profilLabel.setForeground(new java.awt.Color(0, 0, 0));
        profilLabel.setText("> Profil");

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));

        ppLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account.png"))); // NOI18N
        ppLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ppLabel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ppLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ppLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Informasi Akun");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Alamat Default");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(" Nama");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaLabel.setText("Aryo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText(" No Hp");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        noHpLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noHpLabel.setText("088888888");
        noHpLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        fakultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fakultas.setText(" Fakultas ");
        fakultas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jurusan.setText(" Jurusan");
        jurusan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prodi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prodi.setText(" Prodi");
        prodi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText(" Kategori ");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        kategoriLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kategoriLabel.setText("User");

        fakultasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fakultasLabel.setText("Teknik");

        jurusanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jurusanLabel.setText("Teknik Elektro");

        prodiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prodiLabel.setText("Teknik Informatika");

        alamatDefaultLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamatDefaultLabel.setText("Gedung C ,Fakultas Teknik, Universitas Riau");

        editBtn.setBackground(new java.awt.Color(51, 153, 255));
        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.setFocusPainted(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatDefaultLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kategoriLabel)
                                .addComponent(noHpLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(namaLabel))
                            .addGap(200, 200, 200)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fakultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fakultasLabel)
                                .addComponent(jurusanLabel)
                                .addComponent(prodiLabel)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(namaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(noHpLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kategoriLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fakultas)
                            .addComponent(fakultasLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jurusan)
                            .addComponent(jurusanLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodi)
                            .addComponent(prodiLabel))))
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alamatDefaultLabel)
                .addGap(18, 18, 18)
                .addComponent(editBtn)
                .addGap(75, 75, 75))
        );

        jLabel5.setText("Versi 1.1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(profilLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(122, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilLabel)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed

        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        EditProfilDialog dialog = new EditProfilDialog(parent, true, this);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatDefaultLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel fakultas;
    private javax.swing.JLabel fakultasLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jurusan;
    private javax.swing.JLabel jurusanLabel;
    private javax.swing.JLabel kategoriLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel noHpLabel;
    private javax.swing.JLabel ppLabel;
    private javax.swing.JLabel prodi;
    private javax.swing.JLabel prodiLabel;
    private javax.swing.JLabel profilLabel;
    // End of variables declaration//GEN-END:variables
}
