name: "Fitur Admin - Manajemen Kantin"
description: "Form untuk membuat issue fitur Admin"
title: "[ADMIN] "
labels: ["admin", "feature"]

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Fitur Admin - Sistem Kantin Online
        Isi form berikut untuk membuat atau memperbarui fitur Admin.

  - type: input
    id: summary
    attributes:
      label: Ringkasan Fitur
      description: Jelaskan fitur yang ingin dibuat.
      placeholder: Contoh: Admin dapat menambah menu tenant.
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: Deskripsi Detail
      description: Jelaskan alur dan penjelasan fitur.
      placeholder: |
        - Admin membuka dashboard
        - Admin memilih tenant
        - Admin klik tambah menu
        - Admin mengisi nama, harga, stok
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: File atau Class Terkait
      placeholder: |
        - tampilanuser/MenuPanel.java
        - DataPesanan.java
        - Pesanan.java

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - CRUD menu berjalan
        - Data tampil di halaman user
        - Tidak ada error
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: UI sudah dibuat
        - label: Logika backend selesai
        - label: Pengujian manual berjalan
