/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistem.kantin.online;

/**
 *
 * @author aryop
 */
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistem.kantin.online.Cart;
import com.mycompany.sistem.kantin.online.ItemKeranjang;
import com.mycompany.sistem.kantin.online.DataPesanan;

public class checkoutfixed extends javax.swing.JPanel {

    // default metode = Tunai
    private String metodeDipilih = "Tunai";

    public checkoutfixed() {
        initComponents();
        isiTabelDariCart();
    }

    private int hitungTotalDariCart() {
        int total = 0;
        for (ItemKeranjang item : Cart.getItems()) {
            total += item.getTotal();
        }
        return total;
    }

    private void isiTabelDariCart() {
        DefaultTableModel model = (DefaultTableModel) overviewTabel.getModel();
        model.setRowCount(0); // kosongkan dulu

        for (ItemKeranjang item : Cart.getItems()) {
            model.addRow(new Object[]{
                item.getNama(), // kolom "Nama"
                item.getHarga(), // kolom "Harga"
                item.getJumlah(), // kolom "Jumlah"
                item.getTotal() // kolom "Subtotal"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        metodeButtonGroup = new javax.swing.ButtonGroup();
        alamatPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overviewTabel = new javax.swing.JTable();
        batalBtn = new javax.swing.JButton();
        pesanBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tunaiBtn = new javax.swing.JButton();
        transferBtn = new javax.swing.JButton();
        qrisBtn = new javax.swing.JButton();

        alamatPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Alamat Pengantaran");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jl.Bangau Sakti");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Detail Pesanan");

        javax.swing.GroupLayout alamatPanelLayout = new javax.swing.GroupLayout(alamatPanel);
        alamatPanel.setLayout(alamatPanelLayout);
        alamatPanelLayout.setHorizontalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alamatPanelLayout.setVerticalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        overviewTabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        overviewTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(overviewTabel);

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        pesanBtn.setText("Pesan");
        pesanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Metode Pembayaran");

        tunaiBtn.setText("Tunai");
        metodeButtonGroup.add(tunaiBtn);
        tunaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiBtnActionPerformed(evt);
            }
        });

        transferBtn.setText(" Transfer Bank");
        metodeButtonGroup.add(transferBtn);
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        qrisBtn.setText("Qris");
        metodeButtonGroup.add(qrisBtn);
        qrisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrisBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alamatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(116, 116, 116)
                .addComponent(tunaiBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qrisBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(batalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pesanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(alamatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tunaiBtn)
                    .addComponent(transferBtn)
                    .addComponent(qrisBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanBtn)
                    .addComponent(batalBtn))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalBtnActionPerformed

    private void pesanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanBtnActionPerformed
        // Ambil item dari keranjang
        List<ItemKeranjang> items = Cart.getItems();

        if (items.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Keranjang masih kosong.", "Info",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Metode pembayaran dipilih (Tunai / Transfer Bank / Qris)
        String metode = metodeDipilih;

        // Hitung total
        int total = hitungTotalDariCart();

        // Generate kode pesanan otomatis
        String noPesanan = BuatNomorPesanan.next();  // A001, A002, dst

        // Simpan KE RIWAYAT pesanan
        DataPesanan.tambahPesanan(items, metode, total, noPesanan);

        // Kosongkan keranjang setelah pesan
        Cart.kosongkan();

        // Pindah ke panel Pesanan
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent instanceof HomePengguna home) {
            home.changeMainPanel(new pesananPanel());
        }
    }//GEN-LAST:event_pesanBtnActionPerformed

    private void tunaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiBtnActionPerformed
        metodeDipilih = "Tunai";        // TODO add your handling code here:
    }//GEN-LAST:event_tunaiBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        metodeDipilih = "Transfer Bank";        // TODO add your handling code here:
    }//GEN-LAST:event_transferBtnActionPerformed

    private void qrisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrisBtnActionPerformed
        metodeDipilih = "Qris";        // TODO add your handling code here:
    }//GEN-LAST:event_qrisBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alamatPanel;
    private javax.swing.JButton batalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup metodeButtonGroup;
    private javax.swing.JTable overviewTabel;
    private javax.swing.JButton pesanBtn;
    private javax.swing.JButton qrisBtn;
    private javax.swing.JButton transferBtn;
    private javax.swing.JButton tunaiBtn;
    // End of variables declaration//GEN-END:variables
}
