package com.mycompany.sistem.kantin.online;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author aryo
 */
import com.mycompany.sistem.kantin.online.Cart;
import com.mycompany.sistem.kantin.online.ItemKeranjang;

public class detailMenu extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(detailMenu.class.getName());

    /**
     * Creates new form detailMenu
     */
    public detailMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setData(String nama, int harga) {
        namaDetailLabel.setText(nama);
        String hargaMakanan = String.valueOf(harga);
        hargaDetailLabel.setText("Rp " + hargaMakanan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masukKeranjangBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        namaDetailLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        beliBtn = new javax.swing.JButton();
        hargaDetailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Menu");
        setBackground(new java.awt.Color(255, 255, 255));

        masukKeranjangBtn.setText("Masuk Keranjang");
        masukKeranjangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukKeranjangBtnActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayam-geprek.jpeg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        namaDetailLabel.setFont(new java.awt.Font("Fira Sans", 0, 22)); // NOI18N
        namaDetailLabel.setText("Ayam Geprek");

        jLabel2.setText("Warung Kita");

        beliBtn.setText("Beli");
        beliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBtnActionPerformed(evt);
            }
        });

        hargaDetailLabel.setFont(new java.awt.Font("Fira Sans", 0, 20)); // NOI18N
        hargaDetailLabel.setText("sample 1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaDetailLabel)
                            .addComponent(jLabel2)
                            .addComponent(hargaDetailLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(masukKeranjangBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(beliBtn)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaDetailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hargaDetailLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beliBtn)
                            .addComponent(masukKeranjangBtn)))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void beliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBtnActionPerformed
        //// 1. Ambil nama dari label
//        String nama = namaDetailLabel.getText();
//
//        // 2. Ambil harga dari label "Rp 10.000" -> "10000"
//        String hargaText = hargaDetailLabel.getText().replaceAll("[^0-9]", "");
//        int harga = Integer.parseInt(hargaText);
//
//        // 3. Untuk sementara jumlah = 1
//        int jumlah = 1;
//
//        // 4. Tambah ke keranjang
//        Cart.tambahItem(new ItemKeranjang(nama, harga, jumlah));
//
//        // 5. Pindah main panel di HomePengguna ke KeranjangPanel
//        java.awt.Window owner = getOwner();      // owner = frame yang bikin dialog ini
//        if (owner instanceof HomePengguna) {
//            HomePengguna home = (HomePengguna) owner;
//            home.changeMainPanel(new keranjangPanel());   // nama panel keranjangmu
//        }
//
//        // 6. Tutup dialog detail
//        dispose();
// 1. Ambil nama & harga dari label
    String nama = namaDetailLabel.getText();

        // hargaDetailLabel: contoh "Rp 10.000"
        String hargaText = hargaDetailLabel.getText()
                .replace("Rp", "")
                .replace(".", "")
                .trim();
        int harga = Integer.parseInt(hargaText);

        // 2. Tambahkan ke Cart, default jumlah = 1
        Cart.tambahItem(new ItemKeranjang(nama, harga, 1));

        // 3. Cari parent window (HomePengguna)
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);

        // 4. Tutup dialog dulu
        this.dispose();

        // 5. Kalau parent-nya HomePengguna, ganti main panel ke checkoutfixed
        if (parent instanceof HomePengguna) {
            HomePengguna home = (HomePengguna) parent;
            home.changeMainPanel(new checkoutfixed());
        }
    }//GEN-LAST:event_beliBtnActionPerformed

    private void masukKeranjangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukKeranjangBtnActionPerformed
        String nama = namaDetailLabel.getText();
        String hargaText = hargaDetailLabel.getText()
                .replace("Rp", "")
                .replace(".", "")
                .trim();
        int harga = Integer.parseInt(hargaText);

        Cart.tambahItem(new ItemKeranjang(nama, harga, 1));

        // opsional: cuma tutup detail
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_masukKeranjangBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                detailMenu dialog = new detailMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beliBtn;
    private javax.swing.JLabel hargaDetailLabel;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton masukKeranjangBtn;
    private javax.swing.JLabel namaDetailLabel;
    // End of variables declaration//GEN-END:variables
}
