/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistem.kantin.online;

/**
 *
 * @author aryo
 */
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistem.kantin.online.Cart;
import com.mycompany.sistem.kantin.online.ItemKeranjang;

public class keranjangPanel extends javax.swing.JPanel {

    /**
     * Creates new form pesananPanel
     */
    public keranjangPanel() {
        initComponents();
        isiTabelDariCart();
    }

    private void isiTabelDariCart() {
        DefaultTableModel model = (DefaultTableModel) tabelKeranjang.getModel();
        model.setRowCount(0);   // kosongkan tabel

        for (ItemKeranjang item : Cart.getItems()) {
            model.addRow(new Object[]{
                item.getNama(), // kolom "Item"
                item.getHarga(), // kolom "Harga"
                item.getJumlah(), // kolom "Jumlah"
                item.getTotal(), // kolom "Subtotal"
                false // kolom "Aksi" (checkbox)
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKeranjang = new javax.swing.JTable();
        checkoutBtn = new javax.swing.JButton();
        btnPesan1 = new javax.swing.JButton();

        tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Harga", "Jumlah", "Subtotal", "Aksi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelKeranjang);

        checkoutBtn.setBackground(new java.awt.Color(51, 153, 255));
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        btnPesan1.setBackground(new java.awt.Color(51, 153, 255));
        btnPesan1.setForeground(new java.awt.Color(255, 255, 255));
        btnPesan1.setText("Hapus");
        btnPesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutBtn)
                    .addComponent(btnPesan1))
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
//        new checkout().setVisible(true);
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent instanceof HomePengguna) {
            ((HomePengguna) parent).changeMainPanel(new checkoutfixed());
        }
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void btnPesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesan1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan1;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKeranjang;
    // End of variables declaration//GEN-END:variables
}
