package com.mycompany.sistem.kantin.online;

import com.mycompany.sistem.kantin.online.tampilantenant.HomeTenant; 
import com.mycompany.sistem.kantin.online.HomeUser;
import com.mycompany.sistem.kantin.online.HomeKurir;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aryo
 *
 */
//import javax.swing.ImageIcon;
//import java.awt.Image;
public class Login extends javax.swing.JFrame {
//v2
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    //Username dan sandi untuk 'kantin'
    String kantinName = "k";
    String kantinPassword = "k";

    //Username dan sandi untuk 'kurir'
    String kurirName = "kurir";
    String kurirPassword = "kurir123";

    String status = "";

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        loginSebagai = new javax.swing.ButtonGroup();
        btnLogin = new javax.swing.JButton();
        userNameBar = new javax.swing.JTextField();
        lupaPasswordBtn = new javax.swing.JLabel();
        daftarLabel = new javax.swing.JLabel();
        passwordBar = new javax.swing.JPasswordField();
        icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kantinBtn = new javax.swing.JToggleButton();
        kurirBtn = new javax.swing.JToggleButton();
        userBtn = new javax.swing.JToggleButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        btnLogin.setBackground(new java.awt.Color(51, 153, 255));
        btnLogin.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        userNameBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userNameBar.setText(" Masukkan User Name");
        userNameBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameBarFocusLost(evt);
            }
        });
        userNameBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameBarActionPerformed(evt);
            }
        });

        lupaPasswordBtn.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        lupaPasswordBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lupaPasswordBtn.setText("Lupa password?");
        lupaPasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaPasswordBtnMouseClicked(evt);
            }
        });

        daftarLabel.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        daftarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daftarLabel.setText("Belum punya akun? Daftar sekarang");
        daftarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarLabelMouseClicked(evt);
            }
        });

        passwordBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordBarFocusLost(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 6, 0));

        kantinBtn.setBackground(new java.awt.Color(51, 153, 255));
        loginSebagai.add(kantinBtn);
        kantinBtn.setFont(new java.awt.Font("Fira Sans", 1, 17)); // NOI18N
        kantinBtn.setForeground(new java.awt.Color(255, 255, 255));
        kantinBtn.setText("Kantin");
        kantinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kantinBtnActionPerformed(evt);
            }
        });

        kurirBtn.setBackground(new java.awt.Color(51, 153, 255));
        loginSebagai.add(kurirBtn);
        kurirBtn.setFont(new java.awt.Font("Fira Sans", 1, 17)); // NOI18N
        kurirBtn.setForeground(new java.awt.Color(255, 255, 255));
        kurirBtn.setText("Kurir");
        kurirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurirBtnActionPerformed(evt);
            }
        });

        userBtn.setBackground(new java.awt.Color(51, 153, 255));
        loginSebagai.add(userBtn);
        userBtn.setFont(new java.awt.Font("Fira Sans", 1, 17)); // NOI18N
        userBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBtn.setText("User");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(icon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lupaPasswordBtn)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameBar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(kantinBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kurirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(daftarLabel))
                            .addComponent(passwordBar))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kurirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kantinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(userNameBar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(passwordBar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lupaPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daftarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameBarActionPerformed

    private void kurirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurirBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kurirBtnActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        // ambil input dari textfield
        String username = userNameBar.getText();

        // ambil input password (JPasswordField)
        char[] passwordChars = passwordBar.getPassword();
        String password = new String(passwordChars);

        // username & password yang dianggap benar (sementara hardcode)
        // cek
        switch (status) {
            //Jika masuk sebagai Kantin
            case "kantin":
                if (username.equals(kantinName) && password.equals(kantinPassword)) {
                    // Ketika login berhasil
                    new HomeTenant().setVisible(true);
                    this.dispose(); // tutup form login
                } else {
                    // login gagal
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Username atau password salah!",
                            "Login gagal",
                            javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                }

                break;

            //Jika masuk sebagai Kurir
            case "kurir":
                if (username.equals(kurirName) && password.equals(kurirPassword)) {
                    // Ketika login berhasil
                    new HomeKurir().setVisible(true);
                    this.dispose(); // tutup form login
                } else {
                    // login gagal
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Username atau password salah!",
                            "Login gagal",
                            javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                }

                break;

            default:
                //Jika kategori tidak dipilih
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Anda login sebagai apa?!",
                        "Login gagal",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
//                throw new AssertionError();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        status = "user";        // TODO add your handling code here:
    }//GEN-LAST:event_userBtnActionPerformed

    private void kantinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kantinBtnActionPerformed
        status = "kantin";       // TODO add your handling code here:
    }//GEN-LAST:event_kantinBtnActionPerformed

    private void lupaPasswordBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaPasswordBtnMouseClicked
        new HomeUser().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_lupaPasswordBtnMouseClicked

    private void daftarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarLabelMouseClicked

    }//GEN-LAST:event_daftarLabelMouseClicked

    private void userNameBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameBarFocusGained
        String placeholder = " Masukkan User Name";

        if (userNameBar.getText().equals(placeholder)) {
            userNameBar.setText("");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_userNameBarFocusGained

    private void passwordBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordBarFocusLost
//        String placeholder = " Masukkan password";
//
//        if (passwordBar.getText().trim().isEmpty()) {
//            passwordBar.setText(placeholder);
//        }         // TODO add your handling code here:
    }//GEN-LAST:event_passwordBarFocusLost

    private void userNameBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameBarFocusLost
        String placeholder = " Masukkan User Name";

        if (userNameBar.getText().trim().isEmpty()) {
            userNameBar.setText(placeholder);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_userNameBarFocusLost

    private void passwordBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordBarFocusGained
//        String placeholder = " Masukkan password";
//
//        if (passwordBar.getText().equals(placeholder)) {
//            passwordBar.setText("");
//
//        }       // TODO add your handling code here:
    }//GEN-LAST:event_passwordBarFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel daftarLabel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton kantinBtn;
    private javax.swing.JToggleButton kurirBtn;
    private javax.swing.ButtonGroup loginSebagai;
    private javax.swing.JLabel lupaPasswordBtn;
    private javax.swing.JPasswordField passwordBar;
    private javax.swing.JToggleButton userBtn;
    private javax.swing.JTextField userNameBar;
    // End of variables declaration//GEN-END:variables
}
