/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistem.kantin.online;

import javax.swing.table.DefaultTableModel;
import com.mycompany.sistem.kantin.online.DataPesanan;
import com.mycompany.sistem.kantin.online.ItemKeranjang;
import java.util.List;


/**
 *
 * @author aryo
 */
public class PesananPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form pesananPanel
     */
    public PesananPanel1() {
        initComponents();
        isiDariPesananTerakhir();
    }

    private void isiDariPesananTerakhir() {
    DataPesanan pesanan = DataPesanan.getTerakhir();
    if (pesanan == null) {
        // belum ada pesanan
        return;
    }

    // Nomor pesanan
    noPesananLabel.setText("Nomor Pesanan         : " + pesanan.getNoPesanan());

    // Metode pembayaran
    metodePembayaranLabel.setText("Metode Pembayaran : " + pesanan.getMetodePembayaran());

    // Total
    totalLabel.setText("Total Pesanan          : Rp " + pesanan.getTotal());

    // Isi tabel item
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (ItemKeranjang item : pesanan.getItems()) {
        model.addRow(new Object[]{
                item.getNama(),
                item.getHarga(),
                item.getJumlah(),
                item.getTotal()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPesanan1 = new javax.swing.JPanel();
        gambarPesanan1 = new javax.swing.JButton();
        noPesananLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        metodePembayaranLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        cardPesanan1.setBackground(new java.awt.Color(255, 255, 255));
        cardPesanan1.setForeground(new java.awt.Color(0, 0, 0));

        gambarPesanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayam-geprek.jpeg"))); // NOI18N

        noPesananLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noPesananLabel.setForeground(new java.awt.Color(0, 0, 0));
        noPesananLabel.setText("Nomor Pesanan         : A001");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Alamat Pengiriman");

        alamatLabel.setForeground(new java.awt.Color(0, 0, 0));
        alamatLabel.setText("JL. Bangau Sakti");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalLabel.setText("Total Pesanan          : Rp 25.000");

        metodePembayaranLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        metodePembayaranLabel.setForeground(new java.awt.Color(0, 0, 0));
        metodePembayaranLabel.setText("Metode Pembayaran : Tunai");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Detail Pesanan");

        javax.swing.GroupLayout cardPesanan1Layout = new javax.swing.GroupLayout(cardPesanan1);
        cardPesanan1.setLayout(cardPesanan1Layout);
        cardPesanan1Layout.setHorizontalGroup(
            cardPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPesanan1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(cardPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(alamatLabel)
                    .addGroup(cardPesanan1Layout.createSequentialGroup()
                        .addComponent(gambarPesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(cardPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cardPesanan1Layout.createSequentialGroup()
                                .addGroup(cardPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noPesananLabel)
                                    .addComponent(metodePembayaranLabel)
                                    .addComponent(totalLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))))
                    .addComponent(jLabel13))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        cardPesanan1Layout.setVerticalGroup(
            cardPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPesanan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(alamatLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cardPesanan1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cardPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardPesanan1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(noPesananLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(metodePembayaranLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPesanan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(gambarPesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cardPesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cardPesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JPanel cardPesanan1;
    private javax.swing.JButton gambarPesanan1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel metodePembayaranLabel;
    private javax.swing.JLabel noPesananLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
