/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistem.kantin.online.tampilantenant;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Vector;
/**
 *
 * @author riald
 */
public class LaporanPenjualan extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private Vector<Vector<Object>> allData;

    /**
     * Creates new form LaporanPenjualan
     */
    public LaporanPenjualan() {
        initComponents();
        setupLaporanTable();
        setupAksiFilter();
    }
    
    private void setupLaporanTable() {
        String[] columnNames = {"ID", "NAMA PENGGUNA", "WAKTU ORDER", "NAMA PESANAN", "HARGA SATUAN", "JUMLAH", "TOTAL", "STATUS"};
        tableModel = new DefaultTableModel(columnNames, 0);
        
        jTable1.setModel(tableModel);
        loadLaporanData();
    }
    
    public void loadLaporanData() {
        allData = new Vector<>();
        Object[][] rawData = {
            {1001, "Aryo Abi", "2025-11-28 10:30", "Ayam Geprek", 20000, 2, 40000, "Selesai"}, // Hari Ini
            {1002, "Diana Tri", "2025-11-28 10:45", "Nasi Goreng", 18000, 1, 18000, "Selesai"}, // Hari Ini
            {1003, "Riald", "2025-11-27 15:00", "Es Teh Manis", 5000, 1, 5000, "Selesai"},    // Kemarin
            {1004, "Budi", "2025-11-27 16:00", "Jus Pokat", 6000, 1, 6000, "Selesai"}       // Kemarin
        };
        for (Object[] row : rawData) {
            Vector<Object> rowVector = new Vector<>(java.util.Arrays.asList(row));
            allData.add(rowVector);
        }
        displayData(allData);  
    }
    
    private void displayData(Vector<Vector<Object>> dataToDisplay) {
        tableModel.setRowCount(0);
        long totalPendapatan = 0;
        
        for (Vector<Object> row : dataToDisplay) {
            tableModel.addRow(row);
            totalPendapatan += (int) row.get(6);
        }
        String formattedTotal = String.format("%,d", totalPendapatan).replace(",", ".");
        
        jLabel2.setText("TOTAL PENDAPATAN: Rp " + formattedTotal);
        jLabel3.setText("TOTAL TRANSAKSI: " + dataToDisplay.size());
    }
    private void setupAksiFilter() {
        jButton1.addActionListener(e -> jButton1ActionPerformed(e));
        jButton2.addActionListener(e -> jButton2ActionPerformed(e));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("LAPORAN PENJUALAN KANTIN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("TOTAL PENDAPATAN HARI INI:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TOTAL TRANSAKSI HARI INI:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAMA PENGGUNA", "WAKTU ORDER", "NAMA PESANAN", "HARGA SATUAN", "JUMLAH", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("LIHAT HARI INI");

        jButton2.setText("LIHAT SEMUA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(286, 286, 286)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Vector<Vector<Object>> filteredData = new Vector<>();
        String todayDate = "2025-11-28";
        
        for (Vector<Object> row : allData) {
            String date = row.get(2).toString(); // Waktu Order di Indeks 2
                    if (date.startsWith(todayDate)) {
                        filteredData.add(row);
            }
        }
        displayData(filteredData);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        displayData(allData);
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
